yarnPath: .yarn/releases/yarn-rc.js
plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
      spec: '@yarnpkg/plugin-interactive-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
