yarnPath: .yarn/releases/yarn-sources.js

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
      spec: '@yarnpkg/plugin-interactive-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
      spec: '@yarnpkg/plugin-typescript'
