const baseTheme = {
    breakpoints: [32, 48, 64],
    space: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80],
    step: 8,
    fontSizes: [12, 14, 16, 20, 24, 36, 48, 80, 96],
    fontWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    lineHeights: {
        solid: 1,
        title: 1.25,
        copy: 1.5,
    },
    letterSpacings: {
        normal: 'normal',
        tracked: '0.1em',
        tight: '-0.05em',
        mega: '0.25em',
    },
    fonts: {
        serif: 'athelas, georgia, times, serif',
        sansSerif:
            '-apple-system, BlinkMacSystemFont, "avenir next", avenir, "helvetica neue", helvetica, ubuntu, roboto, noto, "segoe ui", arial, sans-serif',
    },
    borders: [0, '1px solid', '2px solid', '4px solid', '8px solid', '16px solid', '32px solid'],
    radii: [0, 2, 4, 16, 9999, '100%'],
    width: [16, 32, 64, 128, 256],
    heights: [16, 32, 64, 128, 256],
    maxWidths: [16, 32, 64, 128, 256, 512, 768, 1024, 1536],
    colors: {
        black: '#000',
        white: '#fff',
        grey: [
            '#121314',
            '#242628',
            '#373A3C',
            '#494D50',
            '#5B6064',
            '#6D7378',
            '#80868C',
            '#94999E',
            '#A1A6AA',
            '#AFB3B6',
            '#BCBFC2',
            '#C9CCCF',
            '#D7D9DB',
            '#E4E6E7',
            '#F2F3F3',
        ],
        blue: [
            '#000B15',
            '#00172B',
            '#002240',
            '#002D56',
            '#00386B',
            '#004480',
            '#004F96',
            '#005BAB',
            '#0570D0',
            '#0E86F2',
            '#3B9AEF',
            '#67AEEE',
            '#90C2EF',
            '#B7D6F2',
            '#DCEBF8',
        ],
        red: [
            '#150001',
            '#2B0001',
            '#400002',
            '#560002',
            '#6B0003',
            '#800003',
            '#960004',
            '#AB0004',
            '#D0050A',
            '#F20E13',
            '#EF3B3F',
            '#EE6769',
            '#EF9092',
            '#F2B7B8',
            '#F8DCDD',
        ],
        success: '#A2EE67',
        error: '#EE6769',
        warning: '#eed868',
        info: '#6887ee',
    },
    time: '300ms',
};

export default {
    ...baseTheme,
    button: {
        borderWidth: 2,
        time: baseTheme.time,
        disabled: {
            color: baseTheme.colors.white,
            bg: baseTheme.colors.grey[14],
            borderColor: baseTheme.colors.grey[12],
        },
        variants: {
            default: {
                color: baseTheme.colors.white,
                colorActive: baseTheme.colors.black,
                bg: baseTheme.colors.black,
                bgActive: baseTheme.colors.white,
                borderColor: baseTheme.colors.black,
                borderColorActive: baseTheme.colors.black,
            },
            primary: {
                color: baseTheme.colors.white,
                colorActive: baseTheme.colors.white,
                bg: baseTheme.colors.blue[7],
                bgActive: baseTheme.colors.blue[6],
                borderColor: baseTheme.colors.blue[7],
                borderColorActive: baseTheme.colors.blue[6],
            },
            secondary: {
                color: baseTheme.colors.white,
                colorActive: baseTheme.colors.white,
                bg: baseTheme.colors.red[8],
                bgActive: baseTheme.colors.red[7],
                borderColor: baseTheme.colors.red[8],
                borderColorActive: baseTheme.colors.red[7],
            },
        },
        sizes: {
            medium: {
                height: baseTheme.space[6],
                padding: baseTheme.space[3],
                fontSize: baseTheme.fontSizes[1],
            },
            small: {
                height: baseTheme.space[4],
                padding: baseTheme.space[2],
                fontSize: baseTheme.fontSizes[0],
            },
        },
    },
};
